services:
  lighttpd:
    image: forallsecure/lighttpd:vulnerable
    network_mode: "host"
    depends_on:
      - snort
    restart: always

  snort:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN  # Give snort required permissions
    network_mode: "host"
    restart: always
