services:
  lighttpd:
    image: forallsecure/lighttpd:vulnerable
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - snort
    restart: always

  snort:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN  # Give snort required permissions
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
